language: node_js
node_js:
- '10'
before_deploy:
- npm run make-distribution
- cd $TRAVIS_BUILD_DIR/lib/main
deploy:
  provider: npm
  email: npm@scispike.com
  skip_cleanup: true
  api_key:
    secure: eXf2oXAytTouSa9w2m5Dmcq+1SuVKi7gcbF4Owk3jvmRJ53td+2D2DaPekC5/kN5U3iwiWK6+cu9yVUZ/NsgXzucZSDK0ePUX7CcV/MyczpIflvtWmczbnAENSNZp0wOsE6nek3+O4/aF1OIvOFPCqoufqSWHwgg5D5laa7LJjKQ0ornlkao9z6HlzFRiUmp5PeqEtsEIUrlS8+Tc6LmiM1MUFNjML1iCfsWdRPghc7bXqLdjuXhQQ2t2wtCtcmXvvNZoYspYJzIXZxnzbCgOl+J63/2LUDjBDJKG5ph62UDdDUx70PxmozltePxt6Q15ouag0lH+0MNUL3ivr/BFZijvFXoz2v0cbNiCJkuEX6BJ+iv5pgVPel7BX4tVgfd6G2AHmylACoAXH3MWa947mXm1N2bC9yfDEQLebIRl7/KT53pEuaFkff+6A3d8095Lji89nTTGl4K76AxGTKnpgVKvyIl04rLcI5PqdlfH5e0805O88e5QaEiTWarYEQy3NbaRTOdA1X9EqOmfj0neI+4KH4RB96r4iZWw0tMmQFKpteU0TIYP0oA81oBVe+dHCqCujmT5OMow24x+7GjGrxHw5hQWAtQKktEIxss2PhWlmlfBnBIKXP+Ihwn9oX3OzX7nD7b1EK6op3CFeX7HLx8+UkKdhAMNplFE8UkJlQ=
  on:
    tags: true
    repo: SciSpike/domain-object-security
